"""Deterministic English stopword list."""

from __future__ import annotations

STOPWORDS: frozenset[str] = frozenset(
    {
        "a",
        "an",
        "and",
        "are",
        "as",
        "at",
        "be",
        "by",
        "for",
        "from",
        "has",
        "he",
        "in",
        "is",
        "it",
        "its",
        "of",
        "on",
        "that",
        "the",
        "to",
        "was",
        "were",
        "will",
        "with",
        "this",
        "but",
        "they",
        "have",
        "had",
        "what",
        "when",
        "where",
        "who",
        "which",
        "or",
        "not",
        "can",
        "all",
        "been",
        "into",
        "than",
        "then",
        "there",
        "their",
        "them",
        "these",
        "those",
        "we",
        "you",
        "your",
        "our",
        "if",
        "so",
        "do",
        "does",
        "did",
        "about",
        "over",
        "under",
        "between",
        "through",
        "during",
        "before",
        "after",
        "above",
        "below",
        "up",
        "down",
        "out",
        "off",
        "again",
        "further",
        "once",
    }
)


def is_stopword(token: str) -> bool:
    """Return True if the normalized token is a stopword."""
    return token in STOPWORDS
